#!/bin/bash
#al="../../adjacency_lists/gg_100x100.al"
al="../../adjacency_lists/g1.al"
#heu="../../adjacency_lists/gg_100x100.heu"
heu="../../adjacency_lists/g1.heu"
src="1"
dst="21"
print_debug="1"

python smastar2.py $al $heu $src $dst $print_debug